Label operator namespace as privileged, add tests
submariner-io/subctl pull request #105
Opened 2022-06-19 18:29 UTC by dfarrell07

This is required for OpenShift 4.11.
    
Also add the privileged label during upgrades.
    
It would be better if these were Go unit tests, but we don't have those
for subctl yet.

2022-06-19 19:28 UTC, dfarrell07 commented
This will fix the timeout (als going to re-trigger): https://github.com/submariner-io/subctl/pull/106

This shows that the tests correctly fail without the fix: https://github.com/dfarrell07/subctl/pull/4

2022-06-19 21:35 UTC, dfarrell07 commented
Re-running again...

2022-06-19 22:22 UTC, tpantelis requested changes

2022-06-19 22:22 UTC, tpantelis commented on pkg/namespace/ensure.go
> +			ns.Labels[k] = v
We shouldn't assume `ns.Labels` is non-nil, ie

```Go
if ns.Labels == nil {
    ns.Labels = map[string]string{}
}

for k, v := range namespaceLabels { 
    ....
}
```

2022-06-20 01:51 UTC, tpantelis approved these changes

2022-06-20 05:46 UTC, sridhargaddam approved these changes

2022-06-20 07:38 UTC, skitt approved these changes

2022-06-20 07:38 UTC, merged

2022-06-27 18:48 UTC, dfarrell07 commented
There was consensus on the dev call today that this should be backported.

2022-06-27 21:09 UTC, dfarrell07 commented
> There was consensus on the dev call today that this should be backported to release-0.12.

This was a complex backport, as the code is in the submariner-operator repo in the release-0.12 branch and it depends on a backport in Admiral.

Admiral backport: https://github.com/submariner-io/admiral/pull/377 
Operator backport: https://github.com/submariner-io/submariner-operator/pull/2117