Enhance --image-override verification
submariner-io/subctl pull request #1086
Opened 2024-03-27 21:59 UTC by tpantelis

The commands that support the `--image-override` flag should verify it up front via the `Arg` function since its user input rather than during the command execution so it doesn't appear as a failure.

Also consolidate the flag setup so each command uses a common `imageOverrides` variable instead of commands defining their own variable.

Fixes https://github.com/submariner-io/subctl/issues/601

2024-03-28 08:28 UTC, skitt requested changes

2024-03-28 08:28 UTC, skitt commented on scripts/test/system.sh
> +_subctl diagnose firewall inter-cluster -kubeconfig "${KUBECONFIGS_DIR}"/kind-config-cluster1 --remoteconfig "${KUBECONFIGS_DIR}"/kind-config-cluster2 --image-override=foo=bar && exit 1
```suggestion
_subctl diagnose firewall inter-cluster --kubeconfig "${KUBECONFIGS_DIR}"/kind-config-cluster1 --remoteconfig "${KUBECONFIGS_DIR}"/kind-config-cluster2 --image-override=foo=bar && exit 1
```

2024-04-01 04:48 UTC, vthapar approved these changes

2024-04-02 09:09 UTC, skitt approved these changes

2024-04-03 12:40 UTC, merged