Add HTTP proxy args to subctl join
submariner-io/subctl pull request #1103
Opened 2024-04-10 13:38 UTC by tpantelis

...and propagate to the operator pod env.

See discussion [here](https://github.com/submariner-io/submariner-operator/pull/3013#issuecomment-2035366304) for more context.

2024-04-10 13:40 UTC, tpantelis commented on pkg/operator/deployment/ensure.go
> +}
I can resurrect https://github.com/submariner-io/submariner-operator/pull/3016 if folks approve internally propagating the settings via the local env instead of passing via function args.

2024-04-12 14:48 UTC, skitt requested changes
It would be good if this also handled `deploy-broker` and `upgrade`, since the operators deployed there might need proxy settings too.

2024-04-12 14:48 UTC, skitt commented on pkg/join/options.go
> +	HTTPNoProxy                   string
How about

```suggestion
	NoProxy                   string
```

to match `httpproxy.Config`?

2024-04-12 14:48 UTC, skitt commented on pkg/operator/deployment/ensure.go
> +	proxyEnv := httpproxy.FromEnvironment()
I would rather have an explicit instance of the options passed in here, rather than using the environment as global variables. Case in point, since this only touches `join`, the end result is that operator deployments from `deploy-broker` and `upgrade` will be silently affected by any local proxy settings.

Relying on environment variables makes it too easy to produce a broken setup without the user knowing why; even if the existing commands are fixed to behave properly, this adds a gotcha to any future sub-command involving an operator deployment.

2024-04-12 15:10 UTC, tpantelis commented on pkg/operator/deployment/ensure.go
> +	proxyEnv := httpproxy.FromEnvironment()
yeah good points - I was a little wary of passing via env vars.

2024-04-15 12:41 UTC, skitt approved these changes

2024-04-23 13:11 UTC, vthapar approved these changes

2024-04-23 13:33 UTC, merged