Change default namespace for diagnose
submariner-io/subctl pull request #126
Opened 2022-06-24 09:59 UTC by Jaanki

diagnose subcommands, kube-proxy-mode and firewall, spawn pods in
"default" ns if it is not provided by the user. For k8s 1.23 and above,
ns without PodSecurity labels throws warnings for the user. It is not
correct to manipulate a ns without the user's consent. Hence change the
"default" ns to "submariner-operator" which is already created with
these labels.

Partially Closes: #119

Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>

2022-06-24 10:32 UTC, skitt requested changes
You also need to change the namespace flag defaults, _e.g._ https://github.com/submariner-io/subctl/blob/devel/cmd/subctl/diagnose.go#L196

2022-06-24 10:35 UTC, Jaanki commented
> You also need to change the namespace flag defaults, _e.g._ https://github.com/submariner-io/subctl/blob/devel/cmd/subctl/diagnose.go#L196

Yes, realised that when I was doing some other related changes. And this got me thinking. Since we are passing a default, the ns would never be nil for diagnose and no need to check for its nil value in internal/pod/schedule.go

2022-06-24 10:54 UTC, skitt commented
> > You also need to change the namespace flag defaults, _e.g._ https://github.com/submariner-io/subctl/blob/devel/cmd/subctl/diagnose.go#L196
> 
> Yes, realised that when I was doing some other related changes. And this got me thinking. Since we are passing a default, the ns would never be nil for diagnose and no need to check for its nil value in internal/pod/schedule.go

That’s a belt-and-suspenders approach — it’s better to check for empty values than to have some other change somewhere else cause things to blow up further down the line.

2022-06-27 13:19 UTC, sridhargaddam requested changes

2022-06-27 13:19 UTC, sridhargaddam commented on pkg/diagnose/firewall.go
> +		sPod, err := spawnSnifferPodOnNode(clusterInfo.ClientProducer.ForKubernetes(), node.Name, constants.OperatorNamespace, "hostname",
We should actually be using the namespace that is read as part of user input.

2022-06-27 13:27 UTC, Jaanki commented on pkg/diagnose/firewall.go
> +		sPod, err := spawnSnifferPodOnNode(clusterInfo.ClientProducer.ForKubernetes(), node.Name, constants.OperatorNamespace, "hostname",
The function `getActiveGatewayNodeName` does not take `namespace` as an argument. Its hard-coded. I just changed the hard-coded value.

2022-06-27 14:09 UTC, sridhargaddam approved these changes

2022-06-27 14:39 UTC, skitt approved these changes

2022-06-27 16:34 UTC, merged