Use `table` printer in `show` commands
submariner-io/subctl pull request #140
Opened 2022-06-30 08:22 UTC by mkolesnik

The code was needlessly complicated, this way it's simpler and has the same effect.

As part of the work:
    * Support for no max length was added.
    * Code now auto formats values (instead of having caller do it).
    * Spacing between columns is 3 (same as kubectl output)
    * Empty tables aren't printed (same as kubectl output)

The commands were greatly simplified by this change, and the print out
is much more aligned with `kubectl` behavior and with each other.

The PR encompasses 2 commits:
1. Overhaul `table.Printer` to be simple & useful
2. Use `table` printer in `show` commands

2022-06-30 08:46 UTC, mkolesnik commented
Example outputs of `subctl show all`:

Before the change:

```shell
Cluster "cluster1"
 ✓ Detecting broker(s)
NAMESPACE                NAME                     COMPONENTS                        GLOBALNET ENABLED   GLOBALNET CIDR       DEFAULT GLOBALNET SIZE    DEFAULT DOMAINS                         
submariner-k8s-broker    submariner-broker        service-discovery, connectivity   true                242.0.0.0/8          65536                                                             

 ✓ Showing Connections
GATEWAY          CLUSTER   REMOTE IP   NAT  CABLE DRIVER  SUBNETS         STATUS     RTT avg.   
cluster2-worker  cluster2  172.19.0.8  no   libreswan     242.254.2.0/24  connected  194.57µs   

 ✓ Showing Endpoints
CLUSTER ID                    ENDPOINT IP     PUBLIC IP       CABLE DRIVER        TYPE            
cluster1                      172.19.0.6      176.230.47.24   libreswan           local           
cluster2                      172.19.0.8      176.230.47.24   libreswan           remote          

 ✓ Showing Gateways
NODE                            HA STATUS       SUMMARY                         
cluster1-worker                 active          All connections (1) are established

 ✓ Showing Network details
    Discovered network details via Submariner:
        Network plugin:  weave-net
        Service CIDRs:   [100.0.0.0/16]
        Cluster CIDRs:   [10.0.0.0/16]
        Global CIDR:     242.254.1.0/24

 ✓ Showing versions
COMPONENT                       REPOSITORY                                            VERSION         
submariner                      localhost:5000                                        local           
submariner-operator             localhost:5000                                        local           
service-discovery               localhost:5000                                        local           
```

After the change:

```shell
Cluster "cluster1"
 ✓ Detecting broker(s)
NAMESPACE               NAME                COMPONENTS                        GLOBALNET   GLOBALNET CIDR   DEFAULT GLOBALNET SIZE   DEFAULT DOMAINS   
submariner-k8s-broker   submariner-broker   service-discovery, connectivity   yes         242.0.0.0/8      65536                                      

 ✓ Showing Connections
GATEWAY           CLUSTER    REMOTE IP    NAT   CABLE DRIVER   SUBNETS          STATUS      RTT avg.     
cluster2-worker   cluster2   172.19.0.8   no    libreswan      242.254.2.0/24   connected   179.748µs    

 ✓ Showing Endpoints
CLUSTER    ENDPOINT IP   PUBLIC IP       CABLE DRIVER   TYPE     
cluster1   172.19.0.6    176.230.47.24   libreswan      local    
cluster2   172.19.0.8    176.230.47.24   libreswan      remote   

 ✓ Showing Gateways
NODE              HA STATUS   SUMMARY                               
cluster1-worker   active      All connections (1) are established   

 ✓ Showing Network details
    Discovered network details via Submariner:
        Network plugin:  weave-net
        Service CIDRs:   [100.0.0.0/16]
        Cluster CIDRs:   [10.0.0.0/16]
        Global CIDR:     242.254.1.0/24

 ✓ Showing versions
COMPONENT             REPOSITORY       VERSION   
submariner            localhost:5000   local     
submariner-operator   localhost:5000   local     
service-discovery     localhost:5000   local     
```

2022-06-30 10:18 UTC, skitt requested changes

2022-06-30 10:18 UTC, skitt commented on internal/show/connections.go
> +	}}
All the changes to this file should be in the second commit.

2022-06-30 10:18 UTC, skitt commented on internal/show/table/table.go
> +	fmt.Printf(template, values...)
Doesn’t

    fmt.Printf(template, row...)

work here?

2022-06-30 10:19 UTC, skitt commented
That was quick, thanks for taking care of this!

2022-06-30 11:32 UTC, mkolesnik commented on internal/show/connections.go
> +	}}
Can't because `connections` is already using the printer

2022-06-30 11:32 UTC, mkolesnik commented on internal/show/table/table.go
> +	fmt.Printf(template, values...)
I wish...

```
cannot use row (variable of type []string) as []interface{} value in argument to fmt.Printf
```

2022-06-30 11:40 UTC, skitt commented on internal/show/connections.go
> +	}}
Oh yes, I can’t read

2022-06-30 11:40 UTC, skitt commented on internal/show/table/table.go
> +	fmt.Printf(template, values...)
Indeed...

2022-06-30 11:40 UTC, skitt approved these changes

2022-07-05 17:28 UTC, dfarrell07 approved these changes
Much simpler and less bug-prone, thanks @mkolesnik!

2022-07-06 07:52 UTC, merged