submariner-daignose: ignore diagnose pod on deployment test
submariner-io/subctl pull request #183
Opened 2022-07-22 21:40 UTC by tomer-shefler

Signed-off-by: Tomer Shefler <sheflertomer@gmail.com>

https://github.com/submariner-io/subctl/issues/130

2022-08-02 16:22 UTC, dfarrell07 commented
CC @mkolesnik as you were a part of the discussion that lead to this PR.

2022-08-08 07:20 UTC, mkolesnik requested changes
Please update the commit message to explain **why** this change is necessary

2022-08-08 07:20 UTC, mkolesnik commented on pkg/diagnose/deployments.go
> +			if pod.Labels["type"] == "submariner-diagnose" {
You should utilize label selectors in `ListOptions` instead (line 170).

You can find examples how to do it in the code.

Also I don't know if type is appropriate, maybe something like `transient: true` to indicate pods that we want to ignore (might be not just the diagnose pods in the future)

2022-08-08 07:20 UTC, mkolesnik commented on pkg/diagnose/deployments.go
> -
This change is unnecessary and also trips the go linter

2022-08-14 11:28 UTC, tomer-shefler commented
Is dependent on https://github.com/submariner-io/subctl/issues/48

2022-08-15 07:38 UTC, mkolesnik commented
Thanks, please follow guidelines for commit message: https://submariner.io/development/code-review/#commit-message-formatting

Also, as part of this fix you should add the label itself as part of diagnose pod deployment.

2022-08-15 09:39 UTC, tomer-shefler commented
> Also, as part of this fix you should add the label itself as part of diagnose pod deployment.

This, was addded in here: https://github.com/submariner-io/submariner-website/pull/814
Is there anywhere else it sholud be added?

2022-08-15 11:16 UTC, mkolesnik commented
> This, was addded in here: [submariner-io/submariner-website#814](https://github.com/submariner-io/submariner-website/pull/814) Is there anywhere else it sholud be added?

The diagnose FW command created the some pods, right?
So its a good idea to label them as such as well (to avoid causing any potential future problems).

2022-08-15 11:25 UTC, tpantelis requested changes

2022-08-15 11:25 UTC, tpantelis commented on pkg/diagnose/deployments.go
> +		LabelSelector: "transient!=true",
We should qualify the label name to be safe.

```suggestion
		LabelSelector: "submariner.io/transient!=true",
```

2022-08-16 04:58 UTC, tomer-shefler commented
> > This, was addded in here: [submariner-io/submariner-website#814](https://github.com/submariner-io/submariner-website/pull/814) Is there anywhere else it sholud be added?
> 
> The diagnose FW command created the some pods, right? So its a good idea to label them as such as well (to avoid causing any potential future problems).
They should be delete at the end of their test (when https://github.com/submariner-io/submariner-operator/pull/2168 is merged), so they won't bother this one. But I could label them either way.

2022-08-18 11:19 UTC, mkolesnik requested changes

2022-08-18 11:19 UTC, mkolesnik commented on pkg/diagnose/deployments.go
> +		LabelSelector: fmt.Sprint("%s!=%s", constants.TransientLabel, constants.TrueLabel),
```suggestion
		LabelSelector: fmt.Sprintf("%s!=%s", constants.TransientLabel, constants.TrueLabel),
```

2022-08-22 14:00 UTC, tpantelis approved these changes

2022-08-23 12:33 UTC, mkolesnik approved these changes
Thanks!

2022-08-30 11:49 UTC, merged

2022-08-30 11:49 UTC, tpantelis commented
I removed the dependency on https://github.com/submariner-io/submariner-operator/pull/2168 as it seems unrelated.