cloud-prepare: Don't open metrics port
submariner-io/subctl pull request #228
Opened 2022-08-19 18:54 UTC by vthapar

With the redesign of metrics, we don't need to open metrics port in the
cloud anymore. This also marks the `metrics-ports` flag as deprecated.

Refer submariner-io/enhancements/pull/128
Depends On submariner-io/submariner-operator/pull/2182

Signed-off-by: Vishal Thapar <5137689+vthapar@users.noreply.github.com>

2022-08-22 08:46 UTC, skitt requested changes

2022-08-22 08:46 UTC, skitt commented on cmd/subctl/cloud.go
> +	_ = cloudPrepareCmd.PersistentFlags().MarkDeprecated("metrics-ports", "Metrics ports no longer required")
Let’s make it clear that `--metrics-ports` has no actual effect any more, it’s not just that it’s no longer required:

```suggestion
	_ = cloudPrepareCmd.PersistentFlags().MarkDeprecated("metrics-ports", "Metrics ports are no longer used, this flag is ignored")
```

2022-08-22 14:20 UTC, tpantelis requested changes

2022-08-22 14:20 UTC, tpantelis commented on cmd/subctl/cloud.go
>  	cloudPrepareCmd.PersistentFlags().Var(&uint16Slice{value: &cloudPorts.Metrics}, "metrics-ports", "Metrics ports")
Then we can remove `cloudPorts.Metrics` altogether:

```suggestion
        ports := []uint16{}
	cloudPrepareCmd.PersistentFlags().Var(&uint16Slice{value: &ports}, "metrics-ports", "Metrics ports")
```

2022-08-23 07:20 UTC, skitt approved these changes

2022-08-23 13:40 UTC, mkolesnik approved these changes

2022-08-23 14:02 UTC, tpantelis approved these changes

2022-08-24 13:34 UTC, merged

2022-09-20 13:53 UTC, dfarrell07 commented
Removing release note label because it's tracked on the epic.