Add suctl diagnose in cluster test
submariner-io/subctl pull request #240
Opened 2022-08-27 08:46 UTC by tomer-shefler

2022-08-31 11:05 UTC, mkolesnik requested changes
Thanks, a few comments

2022-08-31 11:05 UTC, mkolesnik commented on scripts/test/system.sh
> +cat <<EOF | kubectl apply -f -
```suggestion
kubectl apply -f - <<EOF
```

2022-08-31 11:05 UTC, mkolesnik commented on scripts/test/system.sh
> +if [ $retVal -ne 0 ]; then
```suggestion

kubectl wait --for=condition=complete job/submariner-diagnose -n "$subm_ns"  --timeout 120s &
kubectl wait --for=condition=failed job/submariner-diagnose -n "$subm_ns"  --timeout 120s && exit 1 &
if ! wait -n; then
    kill %1 %2 2> /dev/null
```

This avoids waiting for 2 minutes for it to time out in case of failure.

2022-08-31 11:05 UTC, mkolesnik commented on scripts/test/system.sh
> +kubectl delete job submariner-diagnose -n submariner-operator
```suggestion

kubectl delete job submariner-diagnose -n "$subm_ns"
echo "::endgroup::"

```

2022-08-31 11:05 UTC, mkolesnik commented on scripts/test/system.sh
> +        command: ["subctl",  "diagnose", "all", "--in-cluster"]
```suggestion
        command: ["subctl",  "diagnose", "all", "--in-cluster", "--validation-timeout", "20"]
```

2022-08-31 11:05 UTC, mkolesnik commented on scripts/test/system.sh
> +  namespace: submariner-operator
```suggestion
  namespace: ${subm_ns}
```

2022-08-31 11:05 UTC, mkolesnik commented on scripts/test/system.sh
> +        image: quay.io/submariner/subctl:devel
```suggestion
        image: localhost:5000/subctl:local
```

You'll also need to add `subctl` to `PRELOAD_IMAGES` - https://github.com/submariner-io/subctl/blob/devel/Makefile#L27

2022-08-31 11:05 UTC, mkolesnik commented on scripts/test/system.sh
> +    kubectl logs job/submariner-diagnose -n submariner-operator
```suggestion
    kubectl logs job/submariner-diagnose -n "$subm_ns"
```

2022-08-31 11:05 UTC, mkolesnik commented on scripts/test/system.sh
> +# Test subctl diagnose in-cluster
```suggestion
# Test subctl diagnose in-cluster
echo "::group::Validating 'subctl diagnose' in-cluster"
```

This groups everything in CI to make it easier to read

2022-08-31 11:16 UTC, mkolesnik commented
Opened #245 for the failure

2022-09-08 20:07 UTC, mkolesnik requested changes

2022-09-08 20:07 UTC, mkolesnik commented on scripts/test/system.sh
> +	  kill %1 %2 2> /dev/null
```suggestion
    kill %1 %2 2> /dev/null
```

2022-09-08 20:07 UTC, mkolesnik commented on scripts/test/system.sh
> +fi
```suggestion
fi

```

2022-09-08 20:07 UTC, mkolesnik commented on scripts/test/system.sh
> +    kubectl logs job/submariner-diagnose -n ${subm_ns}
As we discussed, it's better to always print the logs.

Try running it right after apply with `-f` flag, and after the log exists you can check the job, which should be done by then, so we might not need all the `wait` logic

2022-09-08 20:08 UTC, mkolesnik commented on scripts/test/system.sh
> +    kubectl logs job/submariner-diagnose -n ${subm_ns}
Also don't forget to exit when the job fails, so that CI shows the failure

2022-09-12 14:12 UTC, mkolesnik reviewed
Thanks, a few nit-picks but overall looks good.

I'll fix the issue that causing the failures and update this when fix is available.

2022-09-12 14:12 UTC, mkolesnik commented on scripts/test/system.sh
> +then
```suggestion
if kubectl get jobs "${job_name}" -n "${subm_ns}" -o jsonpath='{.status.conditions[?(@.type=="Failed")].status}' | grep -q "True"; then
```

2022-09-12 14:12 UTC, mkolesnik commented on scripts/test/system.sh
> +  exit 1
```suggestion
    kubectl delete job "${job_name}" -n "${subm_ns}"
    exit 1
```

2022-09-12 14:12 UTC, mkolesnik commented on scripts/test/system.sh
> +kubectl delete job ${job_name} -n ${subm_ns}
```suggestion
kubectl delete job "${job_name}" -n "${subm_ns}"
```

2022-09-12 14:12 UTC, mkolesnik commented on scripts/test/system.sh
> +kubectl logs job/${job_name} -n ${subm_ns} -f
```suggestion
kubectl logs "job/${job_name}" -n "${subm_ns}" -f
```

2022-09-12 14:28 UTC, mkolesnik commented
Hmm seems that youll need to wait for container to be created anyhow before querying the logs - https://github.com/submariner-io/subctl/runs/8307689456?check_suite_focus=true#step:3:6095

2022-09-19 09:38 UTC, nyechiel commented
@tomer-shefler can you resolve the conflict please? also note that the PR title as a typo (suctl instead of `subctl`)

2022-09-20 10:19 UTC, mkolesnik requested changes

2022-09-20 10:19 UTC, mkolesnik commented on scripts/test/system.sh
> +kubectl wait --for=condition=Ready "job/${job_name}"
```suggestion
kubectl wait --for=condition=Ready -n "$subm_ns" "job/${job_name}"
```

2022-09-20 10:19 UTC, mkolesnik commented on scripts/test/system.sh
> +then
```suggestion
if [[ $(kubectl get jobs "${job_name}" -n "${subm_ns}" -o jsonpath='{.status.conditions[?(@.type=="Failed")].status}') = "True" ]]; then
```

2022-09-20 10:19 UTC, mkolesnik commented on scripts/test/system.sh
> +  exit 1
```suggestion
    kubectl delete job "${job_name}" -n "${subm_ns}"
    exit 1
```

For consistency with indentation in the file

2022-10-06 14:37 UTC, tpantelis commented
globalnet and service discovery need additional privs for the `submariner-diagnose` role: https://github.com/submariner-io/submariner-operator/pull/2264

2022-10-21 07:27 UTC, skitt approved these changes

2022-10-23 08:33 UTC, mkolesnik reviewed
Looks good, one question/suggestion

2022-10-23 08:33 UTC, mkolesnik commented on Makefile
> +deploy: cmd/bin/subctl images
This shouldn't be necessary, why did you add it?

```suggestion
deploy: cmd/bin/subctl
```

2022-10-24 12:27 UTC, tpantelis commented on Makefile
> +deploy: cmd/bin/subctl images
I ran into an issue where I made a change to `subctl` but it wasn't picked up by the `submariner-diagnose` image used for the system tests. This seemed to fix that.

2022-10-25 13:05 UTC, mkolesnik commented on Makefile
> +deploy: cmd/bin/subctl images
The image is always built before deployment, no need to add this.
The problem you had was probably something else (perhaps you had stale shipyard image/files around).

2022-10-25 14:18 UTC, mkolesnik approved these changes

2022-10-25 14:18 UTC, mkolesnik commented on scripts/test/system.sh
> -    make deploy SETTINGS="$SETTINGS" using="${USING}" -o package/.image.subctl
This makes sense :+1:

2022-10-25 15:33 UTC, merged