Export service for system tests
submariner-io/subctl pull request #261
Opened 2022-09-09 20:35 UTC by tpantelis

...so we can properly test `subctl` service discovery functionality. Also deploy service discovery along with globalnet.

2022-09-13 18:02 UTC, dfarrell07 commented on .github/workflows/system.yml
> +        globalnet-and-lighthouse: ['', 'globalnet lighthouse']
Neat idea, combining them like that.

2022-09-13 18:26 UTC, dfarrell07 approved these changes

2022-09-19 14:02 UTC, aswinsuryan approved these changes

2022-09-19 14:26 UTC, mkolesnik requested changes

2022-09-19 14:26 UTC, mkolesnik commented on .github/workflows/system.yml
> +        globalnet-and-lighthouse: ['', 'globalnet lighthouse']
```suggestion
        using: ['', 'globalnet lighthouse']
```

2022-09-19 14:26 UTC, mkolesnik commented on scripts/test/system.sh
> +    sleep 1
No need to `sleep`, just use `sleep_on_fail` from Shipyard

2022-09-19 14:26 UTC, mkolesnik commented on scripts/test/system.sh
> +fi
```suggestion
[[ "${LIGHTHOUSE}" != true ]] || with_context "${clusters[0]}" export_service
```

2022-09-19 15:37 UTC, skitt approved these changes

2022-09-20 09:32 UTC, mkolesnik requested changes
Thanks, a few more suggestions to improve the test

2022-09-20 09:32 UTC, mkolesnik commented on scripts/test/system.sh
> +function export_service() {
```suggestion
function export_service() {
    echo "::group::Running & validating 'subctl export service'"
```

Makes it easier to read the output of the job

2022-09-20 09:32 UTC, mkolesnik commented on scripts/test/system.sh
> +}
```suggestion
    echo "::endgroup::"
}
```

2022-09-20 09:32 UTC, mkolesnik commented on scripts/test/system.sh
> +    return 1
```suggestion
    local cond=$(kubectl get serviceexport nginx-demo --context "$cluster" -o=jsonpath='{.status.conditions[?(@.type=="Valid")]}')
    [[ $(jq -r .status <<< "$cond") = "True" ]] && return 0

    echo "Service not exported: $cond"
    return 1
```

2022-09-20 09:50 UTC, mkolesnik commented on scripts/test/system.sh
> +    cat <<EOF | kubectl --context "$cluster" apply -f -
```suggestion
    kubectl apply -f - <<EOF
```

The context is automatically set by Shipyard since you used `with_context`.
The here-doc can be passed straight to the command, no need to pass it through `cat`.

2022-09-22 16:09 UTC, mkolesnik approved these changes
Looks good, thanks

2022-09-22 16:09 UTC, mkolesnik commented on scripts/test/system.sh
> +
```suggestion
```

nit

2022-09-22 16:09 UTC, mkolesnik commented on scripts/test/system.sh
> +
```suggestion
```

nit

2022-09-23 16:39 UTC, merged