release-note-service-discovery
submariner-io/subctl pull request #268
Opened 2022-09-18 10:53 UTC by LiavSlama

release notes for subctl service-discovery command

2022-09-19 16:45 UTC, dfarrell07 requested changes

2022-09-19 16:45 UTC, dfarrell07 commented on release-notes/20220915-service-discovery.md
> +Added support for Service Discovery objects verification using the subctl diagnose command.
```suggestion
Added `subctl diagnose` verifications for Service Discovery objects.
```

2022-09-20 06:38 UTC, yboaron approved these changes

2022-09-20 08:50 UTC, skitt approved these changes

2022-09-20 14:01 UTC, tpantelis approved these changes

2022-09-20 16:02 UTC, dfarrell07 approved these changes

2022-09-20 16:02 UTC, merged