Release note for #219
submariner-io/subctl pull request #353
Opened 2022-11-03 09:11 UTC by mkolesnik

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2022-11-03 09:15 UTC, skitt approved these changes

2022-11-03 09:34 UTC, sridhargaddam approved these changes

2022-11-03 12:31 UTC, tpantelis requested changes

2022-11-03 12:31 UTC, tpantelis commented on release-notes/20220818-show-versions.md
> +```
This doesn't seem to jive with https://github.com/submariner-io/subctl/issues/219 - it fixed incorrectly reported versions.

```suggestion
The `subctl show` command now correctly reports component image versions when image overrides were specified in `join`.
```

2022-11-07 09:53 UTC, dfarrell07 approved these changes

2022-11-07 17:15 UTC, tpantelis approved these changes

2022-11-07 17:40 UTC, merged