Force delete objects on uninstall if operator pod not running
submariner-io/subctl pull request #542
Opened 2023-02-02 02:17 UTC by tpantelis

The operator is supposed to perform cleanup and remove the finalizer on deletion of the `Submariner` and `ServiceDiscovery` resources. But if it's not running, uninstall would timeout and fail. So uninstall was modified to check if the operator pod is running and, if not, log a warning and force delete the resource by removing the finalizer.

Fixes https://github.com/submariner-io/subctl/issues/31

2023-02-02 12:48 UTC, skitt requested changes
Just a missing space.

2023-02-02 12:48 UTC, skitt commented on pkg/uninstall/all.go
> +				return status.Error(fmt.Errorf("the Submariner operator pod appears to be running but did not"+
```suggestion
				return status.Error(fmt.Errorf("the Submariner operator pod appears to be running but did not "+
```

2023-02-06 15:29 UTC, skitt approved these changes

2023-02-08 17:06 UTC, skitt approved these changes

2023-02-08 19:15 UTC, dfarrell07 approved these changes

2023-02-08 19:16 UTC, merged