Diagnose validate Calico IPPool configuration
submariner-io/subctl pull request #550
Opened 2023-02-07 16:40 UTC by sridhargaddam

Calico supports different types of Overlay networking. Currently, Submariner is validated only when Calico is deployed with VxLAN encapsulation.

In this PR, the diagnose code is enhanced to check the IPPool config and return an appropriate error if the config does not match with Submariner requirements.

Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>

2023-02-07 17:39 UTC, tpantelis approved these changes

2023-02-07 17:51 UTC, skitt requested changes

2023-02-07 17:51 UTC, skitt commented on pkg/diagnose/cni.go
> +func checkSubmarinerPrerequisites(gateway *submv1.Gateway, ippools map[string]unstructured.Unstructured, status reporter.Interface) {
This is Calico-specific, isn’t it? If so, it should have a more specific name.

2023-02-09 08:50 UTC, yboaron approved these changes

2023-02-13 10:30 UTC, sridhargaddam commented
@skitt can you take a relook?

2023-02-13 11:38 UTC, skitt approved these changes

2023-02-13 11:38 UTC, merged