Include image-override as a firewall subcmd
submariner-io/subctl pull request #598
Opened 2023-03-09 12:22 UTC by sridhargaddam

Currently the image-override flag was added to the main subctl diagnose firewall command and was hence ignored when it was passed to the sub-command like intra-cluster, inter-cluster etc. This PR fixes it.

Usage:
subctl diagnose firewall intra-cluster --image-override=...

Partially fixes: https://github.com/submariner-io/subctl/issues/597

2023-03-09 12:39 UTC, skitt requested changes

2023-03-09 12:39 UTC, skitt commented on cmd/subctl/diagnose.go
> +	diagnose.AddFirewallImageOverrideFlag(diagnoseFirewallNatDiscovery.Flags())
Does this work with all three variants? IME sharing a flag variable in this way only works with one of the commands, that’s why there’s a `kube-proxy` variant and a `firewall` variant. I think the fix should be to change the original

    diagnose.AddFirewallImageOverrideFlag(diagnoseFirewallCmd.Flags())

line to

    diagnose.AddFirewallImageOverrideFlag(diagnoseFirewallCmd.PersistentFlags())

2023-03-09 12:40 UTC, sridhargaddam commented
Sample output:

```
subctl diagnose firewall inter-cluster --image-override=submariner-nettest=ip-172-31-30-49.us-east-2.compute.internal:8443/rhacm2/nettest-rhel8@sha256:94dbe33bd8f5030aa828ac133925c4ac3b710f64c26b45ff290ca05dfb2be0c0 --context hub-admin --remotecontext spoke-admin
⢎⠁ Checking if tunnels can be setup on the gateway node of cluster "hub-cluster"
 ✓ Checking if tunnels can be setup on the gateway node of cluster "hub-cluster" 
 ✓ Tunnels can be established on the gateway node of cluster "hub-cluster"

```

2023-03-09 12:58 UTC, sridhargaddam commented on cmd/subctl/diagnose.go
> +	diagnose.AddFirewallImageOverrideFlag(diagnoseFirewallNatDiscovery.Flags())
Yes it works with all the three variants, please see - https://github.com/submariner-io/subctl/pull/598#issuecomment-1461986305

2023-03-09 13:04 UTC, skitt approved these changes

2023-03-09 13:12 UTC, MaxBab approved these changes

2023-03-09 16:52 UTC, dfarrell07 approved these changes

2023-03-09 16:53 UTC, merged

2023-03-10 08:45 UTC, sridhargaddam commented
Backport PR (0.14 branch): https://github.com/submariner-io/subctl/pull/603