Update README to be about subctl repo
submariner-io/subctl pull request #60
Opened 2022-05-18 17:40 UTC by dfarrell07

Was copied from the operator repo, needed to be made about this repo.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

2022-05-18 17:45 UTC, dfarrell07 commented
Preview: https://github.com/dfarrell07/subctl/blob/readme/README.md

2022-05-18 18:01 UTC, tpantelis approved these changes

2022-05-19 04:41 UTC, Jaanki requested changes

2022-05-19 04:41 UTC, Jaanki commented on README.md
> -## Subctl Releases
This portion needs to stay. Its about `subctl` releases. The links would need to be changed.

2022-05-19 13:13 UTC, dfarrell07 commented on README.md
> -## Subctl Releases
I don't think it needs to stay because we link to much better version-specific install docs.

https://submariner.io/operations/deployment/subctl/#installing-specific-versions

2022-05-23 14:28 UTC, maayanf24 approved these changes

2022-05-24 18:16 UTC, dfarrell07 commented
@Jaanki Can you re-review please?

2022-05-25 09:34 UTC, Jaanki approved these changes

2022-05-25 09:35 UTC, merged