Do not create default broker client SA and its RB
submariner-io/subctl pull request #653
Opened 2023-04-06 13:47 UTC by Jaanki

When deploying broker, `submariner-k8s-broker-client` SA is created and bound to `submariner-k8s-broker-cluster`. This SA is not used anywhere.

This PR removes this SA.

2023-04-06 15:43 UTC, skitt requested changes

2023-04-06 15:43 UTC, skitt commented on pkg/broker/rbac.go
>  	submarinerBrokerAdminRole        = "submariner-k8s-broker-admin"
```suggestion
	submarinerBrokerClusterRole = "submariner-k8s-broker-cluster"
	submarinerBrokerAdminRole   = "submariner-k8s-broker-admin"
```

2023-04-17 08:20 UTC, sridhargaddam approved these changes

2023-04-17 11:23 UTC, skitt approved these changes

2023-04-17 12:09 UTC, merged

2023-04-18 13:18 UTC, dfarrell07 commented
Should this be backported @Jaanki?

2023-04-18 17:57 UTC, tpantelis commented
This PR is causing a [system test failure](https://github.com/submariner-io/submariner-operator/actions/runs/4729438042/jobs/8402138154?pr=2601#step:3:1309) in **submariner-operator**. It uses the `submariner-k8s-broker-client` SA/secret to obtain [SUBMARINER_BROKER_CA](https://github.com/submariner-io/submariner-operator/blob/7134634809a8b0407e9ae6198d5fe331c3009a05/scripts/test/system.sh#L16). It's also referenced in [submariner-charts](https://github.com/submariner-io/submariner-charts/blob/61b7d37f76cf19bc81043e0c77fc734696ff244a/submariner-k8s-broker/templates/NOTES.txt#L9). Perhaps we were premature in removing it or the uses/references elsewhere need to removed/updated? @Jaanki @skitt

2023-04-18 21:54 UTC, skitt commented
Let’s revert it for now.

2023-04-18 21:57 UTC, skitt commented
We should have other SAs that can be used for those purposes, let’s update the test and chart docs to use one of those.

2023-04-19 06:45 UTC, Jaanki commented
> Should this be backported @Jaanki?

Not needed @dfarrell07.

2023-04-19 06:56 UTC, Jaanki commented
> We should have other SAs that can be used for those purposes, let’s update the test and chart docs to use one of those.

operator PR: https://github.com/submariner-io/submariner-operator/pull/2602