Make recover-broker-info ST always pass
submariner-io/subctl pull request #663
Opened 2023-04-11 04:15 UTC by Jaanki

When the recovered and original broker-info.subm files don't match, it is difficult to debug in the CI.

This PR prints both the file contents in case they don't match.

The reason of mismatch is at times sequence change of `components`.

This PR also sorts the `components` before writing it to broker-info.sybm file so that the sequence remains same always.

2023-04-11 14:02 UTC, sridhargaddam requested changes

2023-04-11 14:02 UTC, sridhargaddam commented on scripts/test/system.sh
> +  if ! diff <(yq -P eval decoded_broker_info.subm) <(yq -P eval "$DAPPER_SOURCE"/output/decoded_broker_info.subm.orig); then
If the components are not listed in the same order, its still okay from Submariner POV and should not be treated as an error. 

Apart from components not matching, what are the other situations when the contents may not match?

2023-04-12 05:08 UTC, Jaanki commented on scripts/test/system.sh
> +  if ! diff <(yq -P eval decoded_broker_info.subm) <(yq -P eval "$DAPPER_SOURCE"/output/decoded_broker_info.subm.orig); then
> If the components are not listed in the same order, its still okay from Submariner POV and should not be treated as an error.
> 
Yes, but for `diff` it matters. So even if both (original and recovered) broker-info.subm files have exact same content, but the order of `components` is different, `diff` fails and so the system test. This PR makes sure the components are written to broker-info.subm in order so that the order is preserved while recovering and `diff` does not fail.

The components are [originally saved ](https://github.com/submariner-io/subctl/blob/devel/pkg/broker/file.go#L74)as `UnsortedList`. With this PR, I am sorting it before storing for diff's sake.

> Apart from components not matching, what are the other situations when the contents may not match?
broker-info.subm has:

```
type Info struct {
	BrokerURL        string         `json:"brokerURL"`
	ClientToken      *corev1.Secret `omitempty,json:"clientToken"`
	IPSecPSK         *corev1.Secret `omitempty,json:"ipsecPSK"`
	ServiceDiscovery bool           `omitempty,json:"serviceDiscovery"`
	Components       []string       `json:",omitempty"`
	CustomDomains    *[]string      `omitempty,json:"customDomains"`
}
```

diff would fail in below 3 scenarios:
1. If the value of any of the fields don't match. Then its a bug.
2. The sequence of fields stored. We won't have this issue because the sequence will always be preserved as explained in [this stack overflow thread](https://stackoverflow.com/questions/68404867/how-do-i-change-the-position-of-golang-struct-values/68405135#68405135)) and we do [use json.Marshal](https://github.com/submariner-io/subctl/blob/devel/pkg/broker/info.go#L61) while writing to broker-info.subm file.
3. The sequence of `components` is not same. Which this PR solves.

2023-04-12 05:08 UTC, Jaanki commented
This is a backport of https://github.com/submariner-io/subctl/pull/649

2023-04-12 06:36 UTC, sridhargaddam approved these changes

2023-04-12 10:18 UTC, vthapar approved these changes

2023-04-12 10:19 UTC, merged