Create subctl.tar.gz as well
submariner-io/subctl pull request #754
Opened 2023-06-01 07:05 UTC by Jaanki

along with `tar.xz`'s for all supported platforms and architecture. This will be helpful to

1. add krew install support for subctl
2. add subctl to be downloaded from openshift tools download page directly

2023-06-01 09:52 UTC, skitt requested changes

2023-06-01 09:52 UTC, skitt commented on Makefile
> +CROSS_TARBALLS := $(foreach cross,$(CROSS_TARGETS),$(patsubst %,dist/subctl-$(VERSION)-%,$(cross)))
This switches to phony targets which can result in unnecessary builds; we can easily keep concrete targets so let’s do so.

2023-06-01 09:52 UTC, skitt commented on Makefile
> +dist/subctl-%: cmd/bin/subctl-%
This whole recipe should be left as-is, and add

```
dist/subctl-%.tar.gz: cmd/bin/subctl-%
	mkdir -p dist
	tar -czf $@ --transform "s/^cmd.bin/subctl-$(VERSION)/" $<
```

2023-06-01 09:52 UTC, skitt commented on Makefile
> +	#echo $$GOOS $$GOARCH $$components; \
```suggestion
```

2023-06-01 09:54 UTC, skitt commented on Makefile
> +CROSS_TARBALLS := $(foreach cross,$(CROSS_TARGETS),$(patsubst %,dist/subctl-$(VERSION)-%,$(cross)))
```suggestion
CROSS_TARBALLS := $(foreach cross,$(CROSS_TARGETS),$(patsubst %,dist/subctl-$(VERSION)-%.tar.xz,$(cross))) $(foreach cross,$(CROSS_TARGETS),$(patsubst %,dist/subctl-$(VERSION)-%.tar.gz,$(cross)))
```

2023-06-01 11:39 UTC, skitt approved these changes

2023-06-02 09:28 UTC, sridhargaddam approved these changes

2023-06-02 11:38 UTC, tpantelis approved these changes

2023-06-05 04:44 UTC, merged