Create sha256 checksums for all binaries
submariner-io/subctl pull request #786
Opened 2023-06-12 09:25 UTC by Jaanki

Add a make target to create checksums for all subctl binaries created under dist/ directory. Add this new target to `build-cross` target so that the checksums are generated during the automated release process.

Epic: https://github.com/submariner-io/enhancements/issues/182

2023-06-12 10:17 UTC, skitt requested changes

2023-06-12 10:17 UTC, skitt commented on Makefile
> +create_checksums: $(CROSS_TARBALLS)
Don’t use a phony target for a specific file; use the file as the target:

```suggestion
dist/subctl-checksums.txt: $(CROSS_TARBALLS)
```

2023-06-12 10:17 UTC, skitt commented on Makefile
> +	cd dist && sha256sum * >> subctl-checksums.txt
```suggestion
	cd $(@D) && sha256sum $(^F) >> $(@F)
```

2023-06-12 14:51 UTC, skitt approved these changes

2023-06-14 07:49 UTC, sridhargaddam approved these changes

2023-06-15 05:21 UTC, merged