Add build constraints to allow buildling subctl with only non-deploy …
submariner-io/subctl pull request #794
Opened 2023-06-15 07:21 UTC by maayanf24

…commands

2023-06-19 07:14 UTC, Jaanki commented on pkg/cloud/aws/aws.go
> +//go:build !non_deploy
No need to add constraints in this file. Applies to all files under pkg/. Only files under cmd/subctl should have the constraint.

2023-06-19 07:16 UTC, Jaanki requested changes
Constraining only the cobra related files will do the trick. i.e add constraints only to files under `cmd/subctl/*` and not `pkg/*`

2023-06-21 10:12 UTC, skitt requested changes
Please add a system test: build the non-deploy `subctl`, and use it to run `show`, `diagnose` etc.

Please also shorten the commit message:

> Add build constraints for a non-deploy subctl

2023-07-18 11:23 UTC, maayanf24 commented
> Please add a system test: build the non-deploy `subctl`, and use it to run `show`, `diagnose` etc.
> 
> Please also shorten the commit message:
> 
> > Add build constraints for a non-deploy subctl

After discussing with @Jaanki I only added test for `non_deploy_subctl show all` to save the time it would take to also run `diagnose`, `gather` and the other commands

2023-07-18 12:25 UTC, skitt commented
> After discussing with @Jaanki I only added test for `non_deploy_subctl show all` to save the time it would take to also run `diagnose`, `gather` and the other commands

I see you also added sanity tests to make sure that non-deploy `subctl` really can’t `deploy-broker` and `join`, nice!

2023-07-18 12:26 UTC, skitt approved these changes
I’m looking into the linting error.

2023-07-18 12:41 UTC, Jaanki requested changes

2023-07-18 12:41 UTC, Jaanki commented on Makefile
> +	$(GO) build -o cmd/bin/non_deploy_subctl --tags non_deploy ./cmd
Add LDFLAGS like its done at L123 above.

2023-07-18 12:41 UTC, Jaanki commented on scripts/test/system.sh
> +_non_deploy_subctl join --kubeconfig "${KUBECONFIGS_DIR}"/kind-config-cluster1 broker-info.subm --clusterid cluster1 && exit 1
Add similar tests for all ignored commands. That way, we don't miss any. In future, if the build constraint is accidentally removed from some commands, this job should fail.

2023-07-18 13:37 UTC, skitt commented
The linting error is [an upstream bug](https://github.com/denis-tingaikin/go-header/issues/18), I think the only thing we can do (short of using another tool to check headers) is to ignore files with a build constraint. At the end of `.golangci.yml`, add an `issues.exclude-rules` rule for the `goheaders` linter on the relevant paths.

2023-07-19 13:37 UTC, skitt requested changes
Sorry, a few Makefile tweaks I didn’t think of earlier, and a pointer to the goheader bug pushing us to add golangci-lint exclusions.

2023-07-19 13:37 UTC, skitt commented on Makefile
> +	mkdir -p cmd/bin
Let’s use some Make variables to avoid repeating stuff:

```suggestion
	mkdir -p $(@D)
```

2023-07-19 13:37 UTC, skitt commented on Makefile
> +	$(GO) build -o cmd/bin/non_deploy_subctl --tags non_deploy \
```suggestion
	$(GO) build -o $@ --tags non_deploy \
```

2023-07-19 13:37 UTC, skitt commented on .golangci.yml
> +    # Ignore header linting for build constraint
```suggestion
    # Ignore header linting for build constraint
    # See https://github.com/denis-tingaikin/go-header/issues/18
```

2023-07-19 14:19 UTC, maayanf24 commented on Makefile
> +	mkdir -p cmd/bin
Should I update L116 as well?

2023-07-19 14:42 UTC, skitt commented on Makefile
> +	mkdir -p cmd/bin
Ah yes, let’s do that, thanks!

2023-07-20 14:57 UTC, skitt approved these changes

2023-07-25 10:22 UTC, skitt commented
@Jaanki can you re-review?

2023-08-08 13:00 UTC, Jaanki approved these changes

2023-08-14 14:35 UTC, tpantelis approved these changes

2023-08-14 15:14 UTC, merged