Support nat-discovery port validation in subctl diagnose
submariner-io/subctl pull request #81
Opened 2022-06-03 08:36 UTC by sridhargaddam

Currently subctl diagnose ... command validates if metrics port
and tunnel port are allowed on the gateway port. Similar validation
should be done for Nat-discovery port as well. This PR handles that
and users can now use "subctl diagnose firewall nat-discovery ..."
for validating the nat-discovery port.

Fixes issue: https://github.com/submariner-io/subctl/issues/80
Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>

2022-06-03 13:32 UTC, tpantelis requested changes

2022-06-03 13:32 UTC, tpantelis commented on cmd/subctl/diagnose.go
> +			}
```suggestion
		err := diagnose.NatDiscoveryConfigAcrossClusters(
		           clusterInfoFromKubeConfig(args[0]), clusterInfoFromKubeConfig(args[1]),
				diagnoseFirewallOptions, cli.NewReporter())
		exit.OnError(err)
```

2022-06-03 13:32 UTC, tpantelis commented on cmd/subctl/diagnose.go
> +		},
This block is duplicated with L130-143. Can we move it to a function:

```Go
func checkKubeconfigArgs(_ *cobra.Command, args []string) error {
   ....
}
```

```suggestion
		Args: checkKubeconfigArgs,
```

2022-06-03 17:40 UTC, sridhargaddam reviewed
Thanks for reviewing @tpantelis

2022-06-03 17:40 UTC, sridhargaddam commented
This PR can be squashed at the time of merging.

2022-06-03 18:37 UTC, tpantelis requested changes

2022-06-03 18:37 UTC, tpantelis commented on pkg/diagnose/firewall.go
> +func getGatewayIP(clusterInfo *cluster.Info, localClusterID string, status reporter.Interface) string {
This function should return an error and let the caller report it appropriately.

2022-06-03 18:37 UTC, tpantelis commented on pkg/diagnose/firewall_natdiscovery.go
> +	return nil
By not returning an error on failure, the caller won't exit properly. verifyConnectivity should return an error and propagate here.

```suggestion
	err := verifyConnectivity(localClusterInfo, remoteClusterInfo, options, status, NatDiscoveryPort, message)
	if err != nil {
		status.Success("Nat-discovery port is allowed in the cluster %q", localClusterInfo.Name)
	}

	return err
```

2022-06-03 18:37 UTC, tpantelis commented on pkg/diagnose/firewall.go
> +		return ""
```suggestion
		return "", status.Error(err, "Error retrieving gateways from cluster %q", clusterInfo.Name)
```

And similar in other places.

2022-06-03 18:37 UTC, tpantelis commented on pkg/diagnose/firewall.go
> +	}
`getActiveGatewayNodeName` should return an error as well.

```suggestion
	gwNodeName, err := getActiveGatewayNodeName(localClusterInfo, localEndpoint.Spec.Hostname, status)
	if err != nil {
		return err
	}
```

2022-06-03 18:37 UTC, tpantelis commented on pkg/diagnose/firewall.go
> +		return false
```suggestion
		return status.Error(err, "Unable to obtain the local endpoint")
```

etc ...

2022-06-05 12:09 UTC, tpantelis approved these changes

2022-06-06 08:07 UTC, yboaron commented
Q: did you check it when SM deployed in LB mode?
The 'diagnose inter-cluster' didn't work for me on some SM LB deployments

2022-06-06 11:23 UTC, sridhargaddam commented
> Q: did you check it when SM deployed in LB mode? The 'diagnose inter-cluster' didn't work for me on some SM LB deployments

Yes, I noticed that `diagnose inter-cluster ...` is not working in some scenarios and I'm looking into it. I'll push a separate PR for that issue.

2022-06-06 11:47 UTC, yboaron commented
> > Q: did you check it when SM deployed in LB mode? The 'diagnose inter-cluster' didn't work for me on some SM LB deployments
> 
> Yes, I noticed that `diagnose firewall inter-cluster ...` is not working in some scenarios mainly with OCP deployments and I'm looking into it. I'll push a separate PR for that issue.

I have an open  PR(https://github.com/submariner-io/subctl/pull/78) that adds support for LB mode for  inter-cluster case, lets merge this PR and I can update my PR to address also natdiscovery case

2022-06-06 11:48 UTC, yboaron approved these changes

2022-06-06 18:44 UTC, merged

2022-06-07 13:13 UTC, dfarrell07 commented
The PR scrub agrees this should be backported and notes that it will need to be re-implemented on the operator repo.

2022-06-14 19:34 UTC, sridhargaddam commented
Backport PR: https://github.com/submariner-io/submariner-operator/pull/2107