Rename subctl binary to `subctl`
submariner-io/subctl pull request #837
Opened 2023-07-05 10:03 UTC by Jaanki

Currently while building a subctl is binary is named as `subctl-$version-$arch`. This PR does following changes while creating a tar of the binary:

1. Rename the binary to just `subctl`. This is one of the requirements of Krew.
2. Remove the redundant child directory so that on untar'ing the binary is at `subctl-$version-$arch/` path instead of `subctl-$version-$arch/subctl-$version`

Epic: https://github.com/submariner-io/enhancements/issues/182

2023-07-05 10:55 UTC, mkolesnik commented
Don't forget to make any necessary changes in releases repo

2023-07-05 11:33 UTC, skitt commented
> Don't forget to make any necessary changes in releases repo

… and in https://github.com/submariner-io/get.submariner.io/

2023-07-05 11:35 UTC, skitt requested changes

2023-07-05 11:35 UTC, skitt commented on Makefile
> +CROSS_TARGETS := linux-amd64 #linux-arm64 linux-arm linux-s390x linux-ppc64le windows-amd64.exe darwin-amd64 darwin-arm64
```suggestion
CROSS_TARGETS := linux-amd64 linux-arm64 linux-arm linux-s390x linux-ppc64le windows-amd64.exe darwin-amd64 darwin-arm64
```

2023-07-05 11:35 UTC, skitt commented on Makefile
> +CROSS_TARBALLS := $(foreach cross,$(CROSS_TARGETS),$(patsubst %,dist/subctl-$(VERSION)-%.tar.xz,$(cross)))
```suggestion
CROSS_TARBALLS := $(foreach cross,$(CROSS_TARGETS),$(patsubst %,dist/subctl-$(VERSION)-%.tar.xz,$(cross))) \
```

2023-07-05 11:35 UTC, skitt commented on Makefile
> +	tar -cf $@ --transform "s|^cmd/bin/subctl-[^/]*|subctl|" $<
```suggestion
	tar -czf $@ --transform "s|^cmd/bin/subctl-[^/]*|subctl|" $<
```

(`-z` enforces `gzip` compression which is what we want here).

2023-07-05 14:00 UTC, skitt submitted a review, later dismissed

2023-07-10 16:28 UTC, dfarrell07 commented
> Don't forget to make any necessary changes in releases repo

I don't see any PRs relevant to this. Should we have those changes staged before merging this?

2023-07-11 08:14 UTC, skitt commented
> > Don't forget to make any necessary changes in releases repo
> 
> I don't see any PRs relevant to this. Should we have those changes staged before merging this?

That would be preferable, yes.

2023-07-18 13:30 UTC, Jaanki commented
> Don't forget to make any necessary changes in releases repo

No changes are needed in `releases` repo. Point me anything that I needs change and I have missed.

2023-07-18 13:31 UTC, Jaanki commented
> > Don't forget to make any necessary changes in releases repo
> 
> … and in https://github.com/submariner-io/get.submariner.io/

Done https://github.com/submariner-io/get.submariner.io/pull/51

2023-07-19 00:52 UTC, tpantelis approved these changes

2023-07-19 07:24 UTC, skitt approved these changes

2023-07-19 10:57 UTC, sridhargaddam approved these changes

2023-07-19 14:09 UTC, merged