Alert for blocked ESP protocol as part of diagnose
submariner-io/subctl pull request #886
Opened 2023-08-28 11:36 UTC by sridhargaddam

When there is no NAT between the Gateway nodes and Libreswan cable-driver is used, IPsec protocol uses UDP/4500 port for exchanging the keys and ESP for data transfer. As part of subctl diagnose command, this PR now validates if there is a potential issue with ESP and returns appropriate error message.

2023-08-28 12:02 UTC, skitt requested changes

2023-08-28 12:02 UTC, skitt commented on pkg/diagnose/firewall.go
> +	noNatWithIPsec bool, status reporter.Interface,
It’s not obvious what the connection between `noNatWithIPsec` and ESP is — I think this function would be clearer if its parameter name reflected the use within the function:

```suggestion
	espNeeded bool, status reporter.Interface,
```

2023-08-28 12:17 UTC, tpantelis requested changes

2023-08-28 12:17 UTC, tpantelis commented on pkg/diagnose/firewall.go
> +			" on the %q node. Actual pod output: \n%s", destPort, hostname, truncate(sPod.PodOutput)), "")
```
espMsg := "'
If espNeeded {
     espMsg = "and ESP traffic"
}

return status.Error(fmt.Errorf("the tcpdump output from the sniffer pod does not include the message"+
			" sent from client pod. Please check that your firewall configuration allows UDP/%d traffic"+
			"%s on the %q node. Actual pod output: \n%s", destPort, espMsg, hostname, truncate(sPod.PodOutput)), "")

```

2023-08-28 12:30 UTC, skitt requested changes
Thanks, a minor tweak still to ensure that “traffic” and “and” don’t end up stuck together.

2023-08-28 12:30 UTC, skitt commented on pkg/diagnose/firewall.go
> +			espMsg = "and ESP traffic"
```suggestion
			espMsg = " and ESP traffic"
```

2023-08-28 12:32 UTC, tpantelis approved these changes

2023-08-28 16:42 UTC, skitt approved these changes

2023-08-28 17:14 UTC, merged

2023-09-11 18:51 UTC, sridhargaddam commented
Release note PR: https://github.com/submariner-io/submariner-website/pull/1010