Add LICENSE to tars
submariner-io/subctl pull request #979
Opened 2023-10-19 07:12 UTC by Jaanki

Add LICENSE file to the subctl binary tars. This is a requirement to enable krew installation of subctl.

2023-10-19 09:33 UTC, skitt requested changes
Is the requirement for a `LICENSE` file described anywhere? Please add a link to relevant documentation if you can find it.

2023-10-19 09:33 UTC, skitt commented on Makefile
> +	tar -cJf $@ --transform "s|^cmd/bin/subctl-[^/]*|subctl-$(VERSION)/subctl|" --add-file=LICENSE $<
The `LICENSE` file ends up being a prerequisite for the archive, list it as such and change the recipe to include all prerequisites:

```make
dist/subctl-%.tar.xz: cmd/bin/subctl-% LICENSE
	mkdir -p dist
	tar -cJf $@ --transform "s|^cmd/bin/subctl-[^/]*|subctl-$(VERSION)/subctl|" $^
```

2023-10-19 09:33 UTC, skitt commented on Makefile
> +	tar -czf $@ --transform "s|^cmd/bin/subctl-[^/]*|subctl-$(VERSION)/subctl|" --add-file=LICENSE $<
See above.

2023-10-26 07:02 UTC, Jaanki commented
> Is the requirement for a `LICENSE` file described anywhere? Please add a link to relevant documentation if you can find it.

It is not mentioned anywhere but the CI job on [my PR in krew-index repository](https://github.com/kubernetes-sigs/krew-index/pull/3432) (which adds manifest file for subctl) is failing because of missing `LICENSE` file in the tar.

2023-10-26 07:46 UTC, skitt approved these changes

2023-10-26 09:08 UTC, sridhargaddam approved these changes

2023-10-27 05:51 UTC, merged